"use client";
import { useState } from "react";
type Content={stage:string;kind:string;prompt:string;category:string;options:string[];correct:any;points:number;bonusPrompt:string;bonusTarget:number|null;bonusTolerance:number|null};
type Saved={id:string;content:Content;status:string;notes:string;tags:string;usage:{games:{id:string;title:string;phase:string}}[]};
const stages=[['round1','Round one'],['halftime','Halftime'],['round2','Round two'],['final','Final'],['tiebreaker','Tiebreaker']];
const blank=():Content=>({stage:'round1',kind:'single',prompt:'',category:'',options:['','','',''],correct:0,points:10,bonusPrompt:'',bonusTarget:null,bonusTolerance:null});
export default function QuestionBank({gameId,host,onAdded}:{gameId?:string;host?:string;onAdded?:()=>Promise<void>}){
 const [password,setPassword]=useState(''),[unlocked,setUnlocked]=useState(false),[rows,setRows]=useState<Saved[]>([]);
 const [search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[usageFilter,setUsageFilter]=useState('all');
 const [content,setContent]=useState<Content>(blank),[editing,setEditing]=useState<string|null>(null),[editor,setEditor]=useState(false);
 const [status,setStatus]=useState('draft'),[notes,setNotes]=useState(''),[tags,setTags]=useState('');
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState('round1');
 const update=(patch:Partial<Content>)=>setContent(c=>({...c,...patch}));
 async function request(body?:any){const r=await fetch('/api/question-bank',{method:body?'POST':'GET',headers:{'Content-Type':'application/json','x-bank-password':password},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);return j;}
 async function load(){const j=await request();setRows(j.questions);setUnlocked(true);}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 function edit(q?:Saved,duplicate=false){setEditing(q&&!duplicate?q.id:null);setContent(q?{...q.content,options:[...q.content.options]}:blank());setStatus(q?q.status:'draft');setNotes(q?q.notes:'');setTags(q?q.tags:'');setEditor(true);setMessage('');}
 const filtered=rows.filter(q=>(statusFilter==='all'||q.status===statusFilter)&&(usageFilter==='all'||(usageFilter==='never'?q.usage.length===0:q.usage.length>0))&&`${q.content.prompt} ${q.content.category} ${q.tags}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="card"><h2>{gameId?'Add from Question Bank':'Save questions ahead of time'}</h2>
 {!unlocked?<form onSubmit={e=>{e.preventDefault();void run(load);}}><p className="muted">Enter your Question Bank password to prepare or reuse questions.</p><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy||!password}>Open Question Bank</button></form>:<>
 <div className="actions"><button className="primary" disabled={busy} onClick={()=>edit()}>New question +</button><button className="secondary" disabled={busy} onClick={()=>void run(load)}>Refresh</button><button className="secondary" onClick={()=>{setPassword('');setRows([]);setEditor(false);setUnlocked(false);}}>Lock</button></div>
 {editor&&<div className="editanswer"><h3>{editing?'Edit question':'New question'}</h3>
 <label>Suggested part of game<select value={content.stage} onChange={e=>{const stage=e.target.value,n=stage==='halftime'?8:4;update({stage,kind:stage==='halftime'?'order':stage==='tiebreaker'?'number':'single',options:Array(n).fill(''),correct:stage==='halftime'?Array.from({length:n},(_,i)=>i):stage==='tiebreaker'?null:0});}}>{stages.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
 <label>Question type<select value={content.kind} disabled={['halftime','tiebreaker'].includes(content.stage)} onChange={e=>update({kind:e.target.value,correct:e.target.value==='short'?'':e.target.value==='single'?0:e.target.value==='order'?content.options.map((_,i)=>i):[]})}><option value="single">One answer</option><option value="multiple">Select all that apply</option><option value="order">Put in order</option><option value="short">Written answer</option>{content.stage==='tiebreaker'&&<option value="number">Closest number wins</option>}</select></label>
 <label>Category<input maxLength={80} value={content.category} onChange={e=>update({category:e.target.value})}/></label>
 <label>Question<textarea maxLength={300} rows={3} value={content.prompt} onChange={e=>update({prompt:e.target.value})}/></label>
 {['short','number'].includes(content.kind)?<label>Correct answer<input type={content.kind==='number'?'number':'text'} min={0} value={content.correct??''} onChange={e=>update({correct:content.kind==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value})}/></label>:<>
 <div className="choicesform">{content.options.map((o,i)=><label key={i}>Choice {String.fromCharCode(65+i)}<input maxLength={140} value={o} onChange={e=>update({options:content.options.map((x,j)=>i===j?e.target.value:x)})}/></label>)}</div>
 {content.kind==='single'&&<label>Correct choice<select value={content.correct??0} onChange={e=>update({correct:Number(e.target.value)})}>{content.options.map((o,i)=><option key={i} value={i}>{String.fromCharCode(65+i)}. {o}</option>)}</select></label>}
 {content.kind==='multiple'&&<><b>Correct choices (at least two)</b>{content.options.map((o,i)=><label key={i}><input type="checkbox" checked={Array.isArray(content.correct)&&content.correct.includes(i)} onChange={()=>{const a=Array.isArray(content.correct)?content.correct:[];update({correct:a.includes(i)?a.filter((n:number)=>n!==i):[...a,i]});}}/>{o||`Choice ${i+1}`}</label>)}</>}
 {content.kind==='order'&&Array.isArray(content.correct)&&<><b>Correct order</b>{content.correct.map((index:number,i:number)=><div className="orderrow" key={index}><span>{i+1}. {content.options[index]||`Choice ${index+1}`}</span>{[-1,1].map(d=><button key={d} disabled={i+d<0||i+d>=content.options.length} aria-label={d<0?'Move up':'Move down'} onClick={()=>{const a=[...content.correct];[a[i],a[i+d]]=[a[i+d],a[i]];update({correct:a});}}>{d<0?'↑':'↓'}</button>)}</div>)}</>}
 </>}
 <label>Attached bonus question (1 point)<textarea maxLength={300} value={content.bonusPrompt} onChange={e=>update({bonusPrompt:e.target.value})}/></label>
 {content.bonusPrompt&&<div className="choicesform"><label>Bonus correct number<input type="number" min={0} value={content.bonusTarget??''} onChange={e=>update({bonusTarget:e.target.value===''?null:Number(e.target.value)})}/></label><label>Allowed difference (±)<input type="number" min={0} value={content.bonusTolerance??''} onChange={e=>update({bonusTolerance:e.target.value===''?null:Number(e.target.value)})}/></label></div>}
 <label>Host notes<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>Tags<input maxLength={300} placeholder="Halloween, 2026, Movies" value={tags} onChange={e=>setTags(e.target.value)}/></label>
 <label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="draft">Draft (finish later)</option><option value="ready">Ready to use</option></select></label>
 <div className="actions"><button className="primary" disabled={busy} onClick={()=>void run(async()=>{await request({action:'save',id:editing,content,status,notes,tags});await load();setEditor(false);setMessage('Question saved.');})}>Save question</button><button className="secondary" disabled={busy} onClick={()=>setEditor(false)}>Cancel</button></div></div>}
 <label>Search questions, categories or tags<input value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <div className="choicesform"><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All</option><option value="ready">Ready</option><option value="draft">Draft</option></select></label><label>Usage<select value={usageFilter} onChange={e=>setUsageFilter(e.target.value)}><option value="all">All</option><option value="never">Never added to a game</option><option value="used">Added to a game</option></select></label></div>
 {gameId&&<label>Add to<select value={target} onChange={e=>setTarget(e.target.value)}>{stages.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
 <p className="muted">{filtered.length} questions. Usage includes prepared games, even before they start.</p>
 {filtered.map(q=><details className="reviewgroup" key={q.id}><summary>{q.content.prompt||'Untitled draft'} <span className="count">{q.status}</span></summary><p>{q.content.category} · {q.content.kind} · {q.tags}</p><p>Suggested: {stages.find(([v])=>v===q.content.stage)?.[1]}</p><p><b>Correct answer:</b> {['short','number'].includes(q.content.kind)?String(q.content.correct??''):Array.isArray(q.content.correct)?q.content.correct.map((i:number)=>q.content.options[i]).join(q.content.kind==='order'?' → ':', '):q.content.options[q.content.correct]||'Incomplete'}</p>{q.content.bonusPrompt&&<p>Bonus: {q.content.bonusPrompt} · {q.content.bonusTarget} (±{q.content.bonusTolerance})</p>}{q.notes&&<p>Host notes: {q.notes}</p>}<p>{q.usage.length?'Added to: '+Array.from(new Set(q.usage.map(u=>`${u.games.title} (${u.games.id})`))).join(', '):'Never added to a game'}</p><div className="actions"><button className="secondary" disabled={busy} onClick={()=>edit(q)}>Edit</button><button className="secondary" disabled={busy} onClick={()=>edit(q,true)}>Duplicate</button>{gameId&&<button className="primary" disabled={busy||q.status!=='ready'} onClick={()=>void run(async()=>{const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'bankAdd',game:gameId,host,bankPassword:password,bankId:q.id,stage:target})});const j=await r.json();if(!r.ok)throw new Error(j.error);await onAdded?.();await load();setMessage('Question added to your game.');})}>Add to game</button>}</div></details>)}
 </>}
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 </section>;
}
